### ISSUE TITLE
Вопрос про документацию Laravel 8.x-ru

### ISSUE THREAD

**Issue by Sergey-Shabanov** [russsiq/laravel-package-docs-ru#1]
Добрый день Рустам, я так понял, что вы закрыли репозиторий laravel-docs-8.x-ru, от которого у меня есть форк https://github.com/Sergey-Shabanov/laravel-docs-8.x-ru, потому что теперь отображается владельцем другой пользователь (https://github.com/avsbru/laravel-docs-8.x-ru) ?
Мне на емейл упало несколько уведомлений, что есть какое-то обсуждение, но по ссылкам уже отображаются 404 страницы.
Жалко ваш труд конечно, хорошую работу сделали.

**Comment by russsiq** [comment]
Репозиторий закрыт, поддерживаю только локально. Думаю за три месяца до выхода Laravel 9.x там не многое прибавится/поменяется.

**Comment by russsiq** [comment]
@Sergey-Shabanov, привет. Я по поводу [этого](https://github.com/laravel/docs/pull/7109) оно используется для двухколоночного отображения [здесь](https://laravel.com/docs/8.x/homestead#included-software)

**Comment by Sergey-Shabanov** [comment]
Ммм, это получается, что *.md файлы в репозитории документации в первую очередь составляются для парсинга в html на сайте, при этом иногда в ущерб правильной разметки Markdown?

У меня IDE не смогла правильно отобразить документ, ну я и подумал, что Html-стили и разметка по ошибке попали в маркдаун.

Значит с тем документом всё в порядке и я могу закрыть пулреквест?

**Comment by russsiq** [comment]
Да, это исходники документации для основного сайта Laravel. Там еще много где встречается подобное, например [здесь](https://github.com/laravel/docs/blob/8.x/helpers.md#available-methods).

То, что у тебя редактор не распарсил – это другой вопрос. Я просто комментировал подобные строки.

Markdown на гитхаб не запрещает разметку HTML, поэтому она называется [GitHub Flavored Markdown](https://github.github.com/gfm/#html-blocks). Посмотри, может в настройках плагина у редактора есть что-то по этому поводу.

**Comment by russsiq** [comment]
@Sergey-Shabanov Да, это исходники документации для основного сайта Laravel. Там еще много где встречается подобное, например здесь.

То, что у тебя редактор не распарсил – это другой вопрос. Я просто комментировал подобные строки.

Markdown на гитхаб не запрещает разметку HTML, поэтому она называется GitHub Flavored Markdown. Посмотри, может в настройках плагина у редактора есть что-то по этому поводу.

**Comment by Sergey-Shabanov** [comment]
ОК, спасибо за разъяснение

**Comment by russsiq** [comment]
@Sergey-Shabanov, переоткрыл [репо с документацией](https://github.com/russsiq/laravel-docs-ru). Если есть вопросы – добро пожаловать.
